/**
 * OSM tag → 内置地图 style 对照表；kind 与 className/styleId 直接展开在 rule 上。
 *
 * key/value matcher 都允许 exact string 或预编译 RegExp；resolver 后续按 priority 选择唯一 Base。
 * 本文件只声明“什么 tag 选择什么目标”，不包含 Canvas 绘制参数，也不执行正式 Feature 匹配。
 */

import type {BuiltInStyleRule} from "../../../../models/mapsurface/built-in-style-models.js";
import type {CanvasSpatialFeatureType} from "../../../../models/mapsurface/style/base-canvas-style.js";
import type {BUILT_IN_CANVAS_STYLES} from "./built-in-style.js";

export const DEFAULT_CANVAS_BASE_STYLE_IDS = {
  node: "node-default",
  way: "way-default",
  area: "area-default",
} as const satisfies Record<CanvasSpatialFeatureType, keyof typeof BUILT_IN_CANVAS_STYLES>;

export const BUILT_IN_STYLE_RULES = [
  // 固定素材走 SVG image Base；其他 Node CSS 仍使用默认 recipe 提供的 CircleMarker geometry。
  {
    id: "node-volcano",
    renderLayer: "base",
    featureType: "node",
    priority: 155,
    key: "natural",
    value: "volcano",
    kind: "css",
    className: "geomcp-built-in-node-volcano",
    nodeIcon: {asset: "icon/volcano.svg", sizePx: 16},
  },
  {
    id: "node-highway-traffic-signals",
    renderLayer: "base",
    featureType: "node",
    priority: 150,
    key: "highway",
    value: "traffic_signals",
    kind: "css",
    className: "geomcp-built-in-node-traffic-signals",
  },
  {
    id: "node-medical",
    renderLayer: "base",
    featureType: "node",
    priority: 140,
    key: "amenity",
    value: /^(?:hospital|clinic|doctors)$/u,
    kind: "css",
    className: "geomcp-built-in-node-medical",
  },
  {
    id: "node-transit-stop",
    renderLayer: "base",
    featureType: "node",
    priority: 135,
    key: /^(?:highway|public_transport)$/u,
    value: /^(?:bus_stop|platform|stop_position)$/u,
    kind: "css",
    className: "geomcp-built-in-node-transit-stop",
  },
  // 铁路统一使用同一 recipe；机场线保持轻量，管道用稀疏虚线与交通线区分。
  {
    id: "railway-rail",
    renderLayer: "base",
    featureType: "way",
    priority: 130,
    key: "railway",
    value: "rail",
    kind: "canvas",
    styleId: "way-railway-rail",
  },
  {
    id: "aeroway-runway",
    renderLayer: "base",
    featureType: "way",
    priority: 125,
    key: "aeroway",
    value: "runway",
    kind: "canvas",
    styleId: "way-aeroway-runway",
  },
  {
    id: "aeroway-taxiway",
    renderLayer: "base",
    featureType: "way",
    priority: 125,
    key: "aeroway",
    value: "taxiway",
    kind: "canvas",
    styleId: "way-aeroway-taxiway",
  },
  {
    id: "man-made-pipeline",
    renderLayer: "base",
    featureType: "way",
    priority: 120,
    key: "man_made",
    value: "pipeline",
    kind: "canvas",
    styleId: "way-man-made-pipeline",
  },
  // Highway Base 走 Canvas recipe；同 priority 的不同 highway value 互斥，不需要合并 operations。
  {
    id: "highway-motorway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:motorway|motorway_link)$/u,
    kind: "canvas",
    styleId: "way-highway-motorway",
  },
  {
    id: "highway-trunk",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:trunk|trunk_link)$/u,
    kind: "canvas",
    styleId: "way-highway-trunk",
  },
  {
    id: "highway-primary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:primary|primary_link)$/u,
    kind: "canvas",
    styleId: "way-highway-primary",
  },
  {
    id: "highway-secondary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:secondary|secondary_link)$/u,
    kind: "canvas",
    styleId: "way-highway-secondary",
  },
  {
    id: "highway-tertiary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:tertiary|tertiary_link)$/u,
    kind: "canvas",
    styleId: "way-highway-tertiary",
  },
  {
    id: "highway-residential",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "residential",
    kind: "canvas",
    styleId: "way-highway-residential",
  },
  {
    id: "highway-unclassified",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "unclassified",
    kind: "canvas",
    styleId: "way-highway-unclassified",
  },
  {
    id: "highway-living-street",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "living_street",
    kind: "canvas",
    styleId: "way-highway-living-street",
  },
  {
    id: "highway-service",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "service",
    kind: "canvas",
    styleId: "way-highway-service",
  },
  {
    id: "highway-track",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "track",
    kind: "canvas",
    styleId: "way-highway-track",
  },
  {
    id: "highway-pedestrian",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "pedestrian",
    kind: "canvas",
    styleId: "way-highway-pedestrian",
  },
  {
    id: "highway-path",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "path",
    kind: "canvas",
    styleId: "way-highway-path",
  },
  {
    id: "highway-footway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "footway",
    kind: "canvas",
    styleId: "way-highway-footway",
  },
  {
    id: "highway-cycleway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "cycleway",
    kind: "canvas",
    styleId: "way-highway-cycleway",
  },
  {
    id: "highway-bridleway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "bridleway",
    kind: "canvas",
    styleId: "way-highway-bridleway",
  },
  {
    id: "highway-steps",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "steps",
    kind: "canvas",
    styleId: "way-highway-steps",
  },
  {
    id: "highway-default",
    renderLayer: "base",
    featureType: "way",
    priority: 100,
    key: "highway",
    value: /^.+$/u,
    kind: "canvas",
    styleId: "way-highway-road",
  },
  // Area 先让高 priority building 覆盖 landuse，再由对应 recipe 提供 mainColor 与半透明 fill。
  {
    id: "building",
    renderLayer: "base",
    featureType: "area",
    priority: 200,
    key: "building",
    value: /^(?!no$).+$/u,
    kind: "canvas",
    styleId: "area-building",
  },
  {
    id: "landuse-green",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:allotments|flowerbed|forest|grass|recreation_ground|village_green)$/u,
    kind: "canvas",
    styleId: "area-landuse-green",
  },
  {
    id: "landuse-water",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:basin|reservoir|salt_pond)$/u,
    kind: "canvas",
    styleId: "area-landuse-water",
  },
  {
    id: "landuse-residential",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:construction|residential)$/u,
    kind: "canvas",
    styleId: "area-landuse-residential",
  },
  {
    id: "landuse-commercial",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:commercial|landfill|military|retail)$/u,
    kind: "canvas",
    styleId: "area-landuse-commercial",
  },
  {
    id: "landuse-industrial",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: "industrial",
    kind: "canvas",
    styleId: "area-landuse-industrial",
  },
  {
    id: "landuse-agricultural",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:cemetery|farmland|meadow|orchard|plant_nursery|vineyard)$/u,
    kind: "canvas",
    styleId: "area-landuse-agricultural",
  },
  {
    id: "landuse-farmyard",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: "farmyard",
    kind: "canvas",
    styleId: "area-landuse-farmyard",
  },
  {
    id: "landuse-default",
    renderLayer: "base",
    featureType: "area",
    priority: 100,
    key: "landuse",
    value: /^.+$/u,
    kind: "canvas",
    styleId: "area-landuse-default",
  },
] as const satisfies ReadonlyArray<BuiltInStyleRule<keyof typeof BUILT_IN_CANVAS_STYLES>>;
