/**
 * OSM tag → 内置地图 style 对照表；target 可以指向 Canvas recipe 或 CSS class。
 *
 * key/value matcher 都允许 exact string 或预编译 RegExp；resolver 后续按 priority 选择唯一 Base。
 */

import type {BuiltInStyleRule} from "../../../models/built-in-style-models.js";
import type {CanvasSpatialFeatureType} from "../../../models/style/base-canvas-style.js";
import type {BUILT_IN_CANVAS_STYLES} from "./built-in-style.js";

export const DEFAULT_CANVAS_BASE_STYLE_IDS = {
  node: "node-default",
  way: "way-default",
  area: "area-default",
} as const satisfies Record<CanvasSpatialFeatureType, keyof typeof BUILT_IN_CANVAS_STYLES>;

export const BUILT_IN_CANVAS_STYLE_RULES = [
  {
    id: "node-highway-traffic-signals",
    renderLayer: "base",
    featureType: "node",
    priority: 150,
    key: "highway",
    value: "traffic_signals",
    target: {kind: "css", className: "geomcp-built-in-node-traffic-signals"},
  },
  {
    id: "node-rail-station",
    renderLayer: "base",
    featureType: "node",
    priority: 145,
    key: "railway",
    value: /^(?:station|halt|tram_stop)$/u,
    target: {kind: "css", className: "geomcp-built-in-node-rail-station"},
  },
  {
    id: "node-medical",
    renderLayer: "base",
    featureType: "node",
    priority: 140,
    key: "amenity",
    value: /^(?:hospital|clinic|doctors)$/u,
    target: {kind: "css", className: "geomcp-built-in-node-medical"},
  },
  {
    id: "node-transit-stop",
    renderLayer: "base",
    featureType: "node",
    priority: 135,
    key: /^(?:highway|public_transport)$/u,
    value: /^(?:bus_stop|platform|stop_position)$/u,
    target: {kind: "css", className: "geomcp-built-in-node-transit-stop"},
  },
  {
    id: "highway-motorway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:motorway|motorway_link)$/u,
    target: {kind: "canvas", styleId: "way-highway-motorway"},
  },
  {
    id: "highway-trunk",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:trunk|trunk_link)$/u,
    target: {kind: "canvas", styleId: "way-highway-trunk"},
  },
  {
    id: "highway-primary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:primary|primary_link)$/u,
    target: {kind: "canvas", styleId: "way-highway-primary"},
  },
  {
    id: "highway-secondary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:secondary|secondary_link)$/u,
    target: {kind: "canvas", styleId: "way-highway-secondary"},
  },
  {
    id: "highway-tertiary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:tertiary|tertiary_link)$/u,
    target: {kind: "canvas", styleId: "way-highway-tertiary"},
  },
  {
    id: "highway-residential",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "residential",
    target: {kind: "canvas", styleId: "way-highway-residential"},
  },
  {
    id: "highway-unclassified",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "unclassified",
    target: {kind: "canvas", styleId: "way-highway-unclassified"},
  },
  {
    id: "highway-living-street",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "living_street",
    target: {kind: "canvas", styleId: "way-highway-living-street"},
  },
  {
    id: "highway-service",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "service",
    target: {kind: "canvas", styleId: "way-highway-service"},
  },
  {
    id: "highway-track",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "track",
    target: {kind: "canvas", styleId: "way-highway-track"},
  },
  {
    id: "highway-pedestrian",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "pedestrian",
    target: {kind: "canvas", styleId: "way-highway-pedestrian"},
  },
  {
    id: "highway-path",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "path",
    target: {kind: "canvas", styleId: "way-highway-path"},
  },
  {
    id: "highway-footway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "footway",
    target: {kind: "canvas", styleId: "way-highway-footway"},
  },
  {
    id: "highway-cycleway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "cycleway",
    target: {kind: "canvas", styleId: "way-highway-cycleway"},
  },
  {
    id: "highway-bridleway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "bridleway",
    target: {kind: "canvas", styleId: "way-highway-bridleway"},
  },
  {
    id: "highway-steps",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "steps",
    target: {kind: "canvas", styleId: "way-highway-steps"},
  },
  {
    id: "highway-default",
    renderLayer: "base",
    featureType: "way",
    priority: 100,
    key: "highway",
    value: /^.+$/u,
    target: {kind: "canvas", styleId: "way-highway-road"},
  },
  {
    id: "building",
    renderLayer: "base",
    featureType: "area",
    priority: 200,
    key: "building",
    value: /^(?!no$).+$/u,
    target: {kind: "canvas", styleId: "area-building"},
  },
  {
    id: "landuse-green",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:allotments|flowerbed|forest|grass|recreation_ground|village_green)$/u,
    target: {kind: "canvas", styleId: "area-landuse-green"},
  },
  {
    id: "landuse-water",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:basin|reservoir|salt_pond)$/u,
    target: {kind: "canvas", styleId: "area-landuse-water"},
  },
  {
    id: "landuse-residential",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:construction|residential)$/u,
    target: {kind: "canvas", styleId: "area-landuse-residential"},
  },
  {
    id: "landuse-commercial",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:commercial|landfill|military|retail)$/u,
    target: {kind: "canvas", styleId: "area-landuse-commercial"},
  },
  {
    id: "landuse-industrial",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: "industrial",
    target: {kind: "canvas", styleId: "area-landuse-industrial"},
  },
  {
    id: "landuse-agricultural",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:cemetery|farmland|meadow|orchard|plant_nursery|vineyard)$/u,
    target: {kind: "canvas", styleId: "area-landuse-agricultural"},
  },
  {
    id: "landuse-farmyard",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: "farmyard",
    target: {kind: "canvas", styleId: "area-landuse-farmyard"},
  },
  {
    id: "landuse-default",
    renderLayer: "base",
    featureType: "area",
    priority: 100,
    key: "landuse",
    value: /^.+$/u,
    target: {kind: "canvas", styleId: "area-landuse-default"},
  },
] as const satisfies ReadonlyArray<BuiltInStyleRule<keyof typeof BUILT_IN_CANVAS_STYLES>>;
