/**
 * OSM tag → 内置 Canvas Base style 对照表。
 *
 * key/value matcher 都允许 exact string 或预编译 RegExp；resolver 后续按 priority 选择唯一 Base。
 */

import type {BuiltInCanvasStyleRule} from "../../models/built-in-style-models.js";
import type {CanvasSpatialFeatureType} from "../../models/style/base-canvas-style.js";
import type {BUILT_IN_CANVAS_BASE_STYLES} from "./canvas-base-styles.js";

export const DEFAULT_CANVAS_BASE_STYLE_IDS = {
  node: "node-default",
  way: "way-default",
  area: "area-default",
} as const satisfies Record<CanvasSpatialFeatureType, keyof typeof BUILT_IN_CANVAS_BASE_STYLES>;

export const BUILT_IN_CANVAS_STYLE_RULES = [
  {
    id: "highway-motorway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:motorway|motorway_link)$/u,
    styleId: "way-highway-motorway",
  },
  {
    id: "highway-trunk",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:trunk|trunk_link)$/u,
    styleId: "way-highway-trunk",
  },
  {
    id: "highway-primary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:primary|primary_link)$/u,
    styleId: "way-highway-primary",
  },
  {
    id: "highway-secondary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:secondary|secondary_link)$/u,
    styleId: "way-highway-secondary",
  },
  {
    id: "highway-tertiary",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: /^(?:tertiary|tertiary_link)$/u,
    styleId: "way-highway-tertiary",
  },
  {
    id: "highway-residential",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "residential",
    styleId: "way-highway-residential",
  },
  {
    id: "highway-unclassified",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "unclassified",
    styleId: "way-highway-unclassified",
  },
  {
    id: "highway-living-street",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "living_street",
    styleId: "way-highway-living-street",
  },
  {
    id: "highway-service",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "service",
    styleId: "way-highway-service",
  },
  {
    id: "highway-track",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "track",
    styleId: "way-highway-track",
  },
  {
    id: "highway-pedestrian",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "pedestrian",
    styleId: "way-highway-pedestrian",
  },
  {
    id: "highway-path",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "path",
    styleId: "way-highway-path",
  },
  {
    id: "highway-footway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "footway",
    styleId: "way-highway-footway",
  },
  {
    id: "highway-cycleway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "cycleway",
    styleId: "way-highway-cycleway",
  },
  {
    id: "highway-bridleway",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "bridleway",
    styleId: "way-highway-bridleway",
  },
  {
    id: "highway-steps",
    renderLayer: "base",
    featureType: "way",
    priority: 110,
    key: "highway",
    value: "steps",
    styleId: "way-highway-steps",
  },
  {
    id: "highway-default",
    renderLayer: "base",
    featureType: "way",
    priority: 100,
    key: "highway",
    value: /^.+$/u,
    styleId: "way-highway-road",
  },
  {
    id: "building",
    renderLayer: "base",
    featureType: "area",
    priority: 200,
    key: "building",
    value: /^(?!no$).+$/u,
    styleId: "area-building",
  },
  {
    id: "landuse-green",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:allotments|flowerbed|forest|grass|recreation_ground|village_green)$/u,
    styleId: "area-landuse-green",
  },
  {
    id: "landuse-water",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:basin|reservoir|salt_pond)$/u,
    styleId: "area-landuse-water",
  },
  {
    id: "landuse-residential",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:construction|residential)$/u,
    styleId: "area-landuse-residential",
  },
  {
    id: "landuse-commercial",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:commercial|landfill|military|retail)$/u,
    styleId: "area-landuse-commercial",
  },
  {
    id: "landuse-industrial",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: "industrial",
    styleId: "area-landuse-industrial",
  },
  {
    id: "landuse-agricultural",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: /^(?:cemetery|farmland|meadow|orchard|plant_nursery|vineyard)$/u,
    styleId: "area-landuse-agricultural",
  },
  {
    id: "landuse-farmyard",
    renderLayer: "base",
    featureType: "area",
    priority: 110,
    key: "landuse",
    value: "farmyard",
    styleId: "area-landuse-farmyard",
  },
  {
    id: "landuse-default",
    renderLayer: "base",
    featureType: "area",
    priority: 100,
    key: "landuse",
    value: /^.+$/u,
    styleId: "area-landuse-default",
  },
] as const satisfies ReadonlyArray<BuiltInCanvasStyleRule<keyof typeof BUILT_IN_CANVAS_BASE_STYLES>>;
